### ISSUE TITLE
Inspect page - some queries are missing open_req and query_req spans

### ISSUE THREAD

**Issue by marco-scoppetta** [graknlabs/benchmark#211] opened 2019-05-17 11:18 UTC
![image](https://user-images.githubusercontent.com/6430514/57924715-cc0b4500-789d-11e9-9577-1ba32a91c539.png)

http://35.231.146.169:4567/#/inspect/8cbe4c582e0398910cc74f3025e05bc8d4b1bfbf1558087683393

graphType : transitivity_data.gql
query: match (Q-from: $x, Q-to: $y) isa Q; get;

The issue is that all queries should start with open_req and query_req, e.g.:

![image](https://user-images.githubusercontent.com/6430514/57924799-07a60f00-789e-11e9-8769-961e7fe4d858.png)

**Comment by sorsaffari** [comment] 2019-05-19 12:47
@marco-scoppetta @flyingsilverfin could you verify that the `parentId` of all `childSteps` is in fact set correctly by Zipkin?

here is the information I have obtained by looking into the Network tab of Chrom Dev tools:

The payload of the request to get the `childSteps of the given query is as follows:

```
{
  childrenSpans(parentId: ["b8d6c3633fe02f3e", "a5ee5763816ca8a6", "4294cab9aa464544"], limit: 1000) {
    id
    name
    duration
    parentId
    tags {
      childNumber
    }
  }
}
```

I believe the 3 `parentId`s belong to the 3 querySpans, one for each repetition.

The response of this request doesn't contain the `open_req` and `query_req` steps as rightly reported.

**Comment by sorsaffari** [comment] 2019-06-18 17:36
@marco-scoppetta looks like this issue was also caused by the elastic search `limit` constraint. I'm going to close this as we have another issue dedicated to the limit constraint.

**Closed by sorsaffari** 2019-06-18 17:36 UTC
